version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      args:
        APP_NAME: app
      target: development
    container_name: rs_dev_app
    tty: true
    stdin_open: true
    environment:
      USER: rust_name
    volumes:
      - ./:/app:cached
    ports:
      - 5000:5000

  database:
    image: mariadb
    container_name: rs_dev_db
    ports:
      - 3306:3306
    volumes:
      - ./inits/db:/docker-entrypoint-initdb.d
      - ./docker/database/mysql/data:/var/lib/mysql/data:cached
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: sample
      MYSQL_PASSWORD: samplepass
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
#
#  redis:
#    image: redis:alpine3.12
#    container_name: go_dev_redis
#    command: redis-server
#    ports:
#      - 6379:6379
#    volumes:
#      - ./build/docker/redis/data:/data